/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dpedlqyzszmsoyjyvwou"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZWRscXl6c3ptc295anl2d291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MzA5ODMsImV4cCI6MjA5MTIwNjk4M30.jSGS_y5IM5-_qdm-V9RKZ8xN56tKpe0j2ScawdIslfs"